### ISSUE TITLE
Missing Classes!

### ISSUE THREAD

**Issue by Brian151** [roberttkahelin8/Pumpkins-N-Mo-Mod#1]
When .class files decompiled to .java, block comments indicating missing imports were generated, also.
Many of the missing imports are to MineCraft and Forge, but a few are DEFINITELY part of the mod:

mod.mcreator.PumpkinsNMo
mod.mcreator.mcreator_greenFireC
mod.mcreator.mcreator_kArrowBlock
mod.mcreator.mcreator_killitwithnotepad
mod.mcreator.mcreator_magicChickenLauncher
mod.mcreator.mcreator_magicSlime
mod.mcreator.mcreator_magicSlime$EntitymagicSlime
mod.mcreator.mcreator_magicSlimeBall
mod.mcreator.mcreator_magicSlimeBallBlock
mod.mcreator.mcreator_magicSlimeShooterPeTL
mod.mcreator.mcreator_notepad
mod.mcreator.mcreator_powermakerGen
mod.mcreator.mcreator_pumpkinarmor
mod.mcreator.mcreator_purpleMagicSlimeLiquid
mod.mcreator.mcreator_rainbowbow
mod.mcreator.mcreator_specialsword
mod.mcreator.mcreator_stoneGrassBlock
mod.mcreator.mcreator_whiteCow
mod.mcreator.mcreator_whiteCow$EntitywhiteCow
mod.mcreator.mcreator_wireOne
mod.mcreator.mcreator_wrenchtwotwo

Hard to fix something when many pieces are missing

**Comment by roberttkahelin8** [comment]
Aware of issues. You may need the mod file. And you'll need 7-Zip to extract the files.

**Comment by roberttkahelin8** [comment]
Problem! I checked the mod files. all the classes in the mod are actually these files anyway. somehow, mcreator merges needed files that allows forge to understand the language in the mod without minecraft and forge classes.

**Comment by roberttkahelin8** [comment]
This issue solved.

**Comment by roberttkahelin8** [comment]
This issue solved.
